### ISSUE TITLE
Use N1ql to get original document

### ISSUE THREAD

**Issue by mreis92** [fogine/couchbase-odm#18]
Hello! I have a model where I use indexes:

```
		indexes: {
			refDocs: {
				getByName: { keys: ['name'] }
			}
		}
```

and I wonder if it is possible to use N1QL in order to retrieve the original document. If I try to use the key of the refDoc, the query response is a binary, which I don't know how to process. Is this something that it is possible to do?

**Comment by fogine** [comment]
Hello @mreis92 ,

In the request of what do you get binary response? Could you provide an example code  of the request you get the binary response from? Also, when you try to get binary data, the data are `base64` encoded... you need to decode it first... if you use the `couchbaseSDK` or this `ODM` to make the request, the response you get should have been already decoded...

**Comment by mreis92** [comment]
Hi @fogine, sorry, I could have been clearer, I am using the N1QL console provided by the management server. 

Let's say I have a ref doc with the key: `Brand::name::test`, then the following N1QL query:

`SELECT * FROM bucket USE KEYS "Brand::name::test"`

and it returns: 

```
[
  {
    "b": "<binary (43 b)>"
  }
]
```

Ideally, I would like to see as result the original document. Do I need an additional processing step? Or are the results of the management console different from using the SDK eventually?

**Comment by fogine** [comment]
My apologies, @mreis92 . I've thought that the Couchbase handles `binary` documents in the same way as it does when using `Views`. Apparently, `N1QL` does not support binary documents. Currently it's not possible to get binary data via `N1QL`.

>N1QL does not parse the binary data. The returned value only signifies that the value is a binary value. For example, "\u003cbinary (size_in_bytes b)\u003e", where size_in_bytes signifies the size of the binary data in bytes. You can use the TYPE() function to retrieve the type of the value as binary. Functions that return metadata such as META() still operate as expected. However, operations on binary data are limited.

However, you don't need to query a `refDoc` in order to get the parent document via a `name`. It's unnecessary.

I'd create primary / secondary index on the `bucket` and then query the parent document directly:

```sql
create primary index on default using gsi; # create primary index as `Glocal secondary index` on the `default` bucket

create index brand_name_idx on default(name) where _type="Brand" using gsi; # create name index on documents of type Brand

select * from default where name="test"; 
```

More information about primary indexes [HERE](http://developer.couchbase.com/documentation/server/current/n1ql/n1ql-language-reference/createprimaryindex.html)

The best way how to get the `brand` document via it's name would be making use of  [getByRefDoc method](https://fogine.github.io/couchbase-odm/tutorial-3b.refDocIndexes.html) on the `Brand` Model in the `CouchbaseODM`
